// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56jrAWXIN3GpU99tSQdAe3JZCwK8Mgyg',
    appId: '1:390636144434:web:04ab994a317396ebf9392b',
    messagingSenderId: '390636144434',
    projectId: 'github-eb01f',
    authDomain: 'github-eb01f.firebaseapp.com',
    storageBucket: 'github-eb01f.appspot.com',
    measurementId: 'G-GMXX7YF3DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYm2WawIFmjYuCFbGednLC0bP4ggnfxGs',
    appId: '1:390636144434:android:bc72b86a0356d6caf9392b',
    messagingSenderId: '390636144434',
    projectId: 'github-eb01f',
    storageBucket: 'github-eb01f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdQRSwN2_ckguV1zg1tRjNrq91WjZl10',
    appId: '1:390636144434:ios:67e3d9900e45e561f9392b',
    messagingSenderId: '390636144434',
    projectId: 'github-eb01f',
    storageBucket: 'github-eb01f.appspot.com',
    iosClientId: '390636144434-0jmtfuun6s26dbr03smkg8e9hru3fpvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdQRSwN2_ckguV1zg1tRjNrq91WjZl10',
    appId: '1:390636144434:ios:67e3d9900e45e561f9392b',
    messagingSenderId: '390636144434',
    projectId: 'github-eb01f',
    storageBucket: 'github-eb01f.appspot.com',
    iosClientId: '390636144434-0jmtfuun6s26dbr03smkg8e9hru3fpvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
